# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.3

cache:
  paths:
  - vendor/

before_script:
  - gem install jekyll bundler --install-dir vendor/ruby/2.3.0
  - gem install sass --no-user-install --install-dir vendor/ruby/2.3.0
  - bundle install --path vendor

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
  - bundle exec jekyll serve --host=0.0.0.0 -d public
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - LANG="en_GB.UTF-8" LC_ALL="en_GB.UTF-8" bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master
