---
title: justin.hartman.me
timezone: Africa/Johannesburg
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Justin Hartman
description: Justin Hartman is a South African entreprenuer who has been growing and innovating in the digital landscape for more than seventeen years. Having pioneered and spearheaded a number of great businesses; Social Code and Afrigator, Justin Hartman is a true digital visionary.
sass:
  style: expanded
avatar: https://avatars2.githubusercontent.com/u/717118?v=3&s=460
author_links:
  facebook: https://www.facebook.com/justin.hartman.me
  flickr: https://www.flickr.com/photos/justinhartman/
  github: https://www.github.com/justinhartman
  instagram: https://www.instagram.com/justin.hartman/
  linkedin: https://www.linkedin.com/in/justinhartman
  pinterest: https://za.pinterest.com/iamjustinhartman/
  twitter: https://twitter.com/justinhartman
  stackoverflow: https://stackoverflow.com/users/1322242/justinhartman
disqus: iamjustinhartman
google_analytics: UA-100937492-4
baseurl: 
permalink: "/:title/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CNAME
url: "http://justin.hartman.me"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at
