url                           : "https://justinhartman.co"
baseurl                       :
permalink                     : "/:title"
timezone                      : Africa/Johannesburg
encoding                      : utf-8
collections:
  posts:
    title                     : Posts
    output                    : true
    permalink                 : /:categories/:title.html
  pages:
    title                     : Pages
    output                    : true
    permalink                 : /:title.html
  projects:
    title                     : Projects
    output                    : true
    permalink                 : /:collection/:title.html
  linux:
    title                     : Linux
    output                    : true
    permalink                 : /:collection/:categories/:title.html
  technical:
    title                     : Technical
    output                    : true
    permalink                 : /:collection/:categories/:title.html
  playground:
    title                     : Playground
    output                    : true
# Basic site structure / setup
kramdown:
  input                       : GFM
  syntax_highlighter          : rouge
  syntax_highlighter_opts:
    css_class                 : highlight
github: [metadata]
exclude:
  - .editorconfig
  - .git
  - .gitattributes
  - .gitignore
  - .nova
  - .travis.yml
  - .wakatime-project
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - TODO.md
  - _drafts
  - _sass
  - _templates
  - assets/images/templates
  - script
  - vendor
# Plugins
plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-algolia
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - octopress
  - jekyll-minifier
# Theme configuration
remote_theme                  : mmistakes/minimal-mistakes
minimal_mistakes_skin         : "justin" # (contrast or neon. justin is based off contrast)
locale                        : "en_GB"
title                         : "Justin Hartman"
title_separator               : "-"
name                          : "Justin Hartman"
description                   : "Justin Hartman is a South African entreprenuer who has been growing and innovating in the digital landscape for more than seventeen years. Having pioneered and spearheaded a number of great businesses; Social Code and Afrigator, Justin Hartman is a true digital visionary."
repository                    : justinhartman/minimal-mistakes
# Default settings for Collections
teaser                        : "/assets/images/general/580x300.jpg"
breadcrumbs                   : true
defaults:
  - scope:
      path                    : ""
      type                    : posts
    values:
      read_time               : true
      comments                : true
      layout                  : single
      author_profile          : true
      share                   : true
      related                 : false
      toc                     : true
      toc_label               : "On this Page"
      toc_icon                : bookmark
      sitemap:
        changefreq            : monthly
        priority              : 0.9
  - scope:
      path                    : ""
      type                    : pages
    values:
      layout                  : single
      comments                : false
      author_profile          : true
      read_time               : true
      share                   : false
      toc                     : false
      sitemap:
        changefreq            : yearly
        priority              : 0.8
  - scope:
      path                    : ""
      type                    : projects
    values:
      layout                  : single
      comments                : true
      author_profile          : false
      read_time               : true
      share                   : true
      toc                     : false
      related                 : false
      sitemap:
        changefreq            : monthly
        priority              : 0.9
  - scope:
      path                    : ""
      type                    : linux
    values:
      layout                  : single
      comments                : true
      author_profile          : true
      read_time               : true
      share                   : true
      toc                     : true
      toc_label               : "On this Page"
      toc_icon                : bookmark
      related                 : false
      sitemap:
        changefreq            : monthly
        priority              : 0.9
  - scope:
      path                    : ""
      type                    : technical
    values:
      layout                  : single
      comments                : true
      author_profile          : true
      read_time               : true
      share                   : true
      toc                     : true
      toc_label               : "On this Page"
      toc_icon                : bookmark
      related                 : false
      sitemap:
        changefreq            : monthly
        priority              : 0.9
words_per_minute              : 200
# Archive Pages
category_archive:
  type                        : liquid
  path                        : /categories/
tag_archive:
  type                        : liquid
  path                        : /tags/
# Pagination
# paginate                      : 5
# paginate_path                 : /everything/page:num/
# Comments
comments:
  provider                    : facebook
  disqus:
    shortname                 :
  facebook:
    appid                     : 112996658724332
    num_posts                 : 5
    colorscheme               : light
reCaptcha:
  siteKey                     : 6LfjtkwUAAAAAEmkBKSJ1jsVlf6qKXPrqqjGgv1i
  secret                      : 6LfjtkwUAAAAAPeJyxISYz8aFsbLM2Qt7ZmZXSGJ
atom_feed:
  path                        : https://justinhartman.co/feed.xml
# Search Config
search                        : true
search_full_content           : true
search_provider               : lunr # or use: algolia
# SEO Related
google_site_verification      : 0GXMKHh4Cau6H41dlMLKfS08dFG9d72ZtIAp5ds2lX4
bing_site_verification        : C7D6FF50BE25A9929352025D72EA0ED5
yandex_site_verification      : d8aaabb36be0cab8
naver_site_verification       : cff9b1642528de3b4703608b5c9ae651d8ed9307
# alexa_site_verification       :
# Social Sharing
twitter:
  username                    : justinhartman
facebook:
  username                    : justinhartman.co
  app_id                      : 112996658724332
  publisher                   : 566420412
og_image                      : "/assets/images/general/justin-hartman.jpeg"
social:
  type                        : Person
  name                        : Justin Hartman
  links:
  - https://www.facebook.com/justinhartman.co
  - https://www.flickr.com/photos/justinhartman
  - https://www.github.com/justinhartman
  - https://www.instagram.com/justin.hartman/
  - https://www.linkedin.com/in/justinhartman
  - https://za.pinterest.com/iamjustinhartman
  - https://twitter.com/justinhartman
  - https://stackoverflow.com/users/1322242/justinhartman
  - http://whoswho.co.za/justin-hartman-30052-30052
  - https://www.crunchbase.com/person/justin-hartman
# Analytics
analytics:
  provider                    : google # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id               : UA-100937492-4
# Site Author
author:
  name                        : "Justin Hartman"
  avatar                      : "/assets/images/general/justin-hartman.jpeg"
  bio                         : "Justin Hartman is a South African entreprenuer who has been innovating in the digital landscape for more than seventeen years. Having pioneered and spearheaded a number of great businesses; Social Code and Afrigator, Justin Hartman is a true digital visionary."
  location                    : "South Africa"
  email                       : justinhartman@fire.fundersclub.com
  uri                         : https://justinhartman.co
  home                        : / # null (default), "absolute or relative url to link to author home"
  #bitbucket                  : justinhartman
  flickr                      : justinhartman
  facebook                    : justinhartman.co
  github                      : justinhartman
  google_plus                 : 115788405127011300666
  instagram                   : justin.hartman
  linkedin                    : justinhartman
  twitter                     : justinhartman
# Octopress Configuration
# Default extension for new posts and pages
post_ext: md
page_ext: md
# Default templates for posts and pages
post_layout: single
page_layout: archive
# Format titles with titlecase?
titlecase: true
# Change default template file (in _templates/)
post_template: life
page_template: page
draft_template: draft
# Jekll Minifier Settings.
jekyll-minifier:
  exclude:
    - feed.xml
    - feed.xslt.xml
    - humans.txt
    - robots.txt
    - sitemap.xml
    - sitemap.xsl
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: false        # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)
