source 'https://rubygems.org'
gem 'github-pages'
gem 'minimal-mistakes-jekyll'
gem 'octopress', '~> 3.0'
group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate'
  gem 'jekyll-algolia'
  gem 'jekyll-include-cache'
  gem 'jekyll-last-modified-at'
  gem 'jekyll-redirect-from'
  gem 'jemoji'
  gem 'jekyll-mentions'
  gem 'jekyll-import'
end
