[build]
  base = ""
  publish = "_site/"
  command = "bundle exec jekyll build"

# https://github.com/chrisdwheatley/netlify-plugin-image-optim#readme
# [[plugins]]
# package = "netlify-plugin-image-optim"

# https://github.com/munter/netlify-plugin-hashfiles#readme
[[plugins]]
package = "netlify-plugin-hashfiles"

  [plugins.inputs]
  entryPoints = [
    "*.html"
  ]
  # Directory where content-addressable files are moved and immutable cache-headers are set
  staticDir = "/static"


# A basic redirect rule
[[redirects]]
  from = "/*"
  to = "https://justinhartman.co/:splat"
  status = 301

# A redirect rule with all the supported properties
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"

  # The default HTTP status code is 301, but you can define a different one.
  # status = 302

  # By default, redirects won't be applied if there's a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  # force = true

  # Redirect from /old-path?id=123 to /new-path. Each combination of query
  # params needs to be defined in a separate [[redirects]] block.
  # More information at https://docs.netlify.com/routing/redirects/redirect-options/#query-parameters
  # query = {id = ":id"}
