#!/usr/bin/env bash
#
# Install the files and run htmlproof.
#
# Author: Justin Hartman <justin@hartman.me>
# Version: 1.0.0
# Copyright (c) 2020 Justin Hartman <https://hartman.me>
#

# halt script on error
set -e

#######################################
# Build the site.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
build() {
    bundle exec jekyll build
}

#######################################
# Run htmlproof to validate site.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
proof() {
    bundle exec htmlproofer ./_site \
        --disable-external \
        --allow-hash-href \
        --ignore-files '/kitchen-sink\.html/'
}

build
proof
